/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: { Cube041: THREE.Mesh; Cube041_1: THREE.Mesh };
  materials: { ['IMac-Body.001']: THREE.MeshStandardMaterial };
};

export function AppleKeyboardModel(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/apple-keyboard-transformed.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube041.geometry} material={materials['IMac-Body.001']} />
      <mesh geometry={nodes.Cube041_1.geometry} material={nodes.Cube041_1.material} />
    </group>
  );
}

useGLTF.preload('/models/apple-keyboard-transformed.glb');
