/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: { Vert001: THREE.Mesh };
  materials: { ['IMac-Body']: THREE.MeshStandardMaterial };
};

export function AppleMouseModel(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/apple_mouse.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Vert001.geometry}
        material={materials['IMac-Body']}
        position={[0.235, 0.726, 0.159]}
        rotation={[Math.PI, -0.105, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload('/models/apple_mouse.glb');
