/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: { Adjustable_Desk: THREE.Mesh };
  materials: { ['Material.001']: THREE.MeshStandardMaterial };
};

export function DeskModel(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/desk_textured-transformed.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Adjustable_Desk.geometry}
        material={materials['Material.001']}
      />
    </group>
  );
}

useGLTF.preload('/models/desk_textured-transformed.glb');
