/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: { Mesh13: THREE.Mesh };
  materials: { PaletteMaterial001: THREE.MeshStandardMaterial };
};

export function IMacBlue(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/imac_blue-transformed.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh13.geometry}
        material={materials.PaletteMaterial001}
      />
    </group>
  );
}

useGLTF.preload('/models/imac_blue-transformed.glb');
