/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: { Cube017: THREE.Mesh; Cube017_1: THREE.Mesh; Cube017_2: THREE.Mesh };
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.006']: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
  };
};

export function MechKeyboardModel(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/mech-keyboard-transformed.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials['Material.002']}
      />
      <mesh
        geometry={nodes.Cube017_1.geometry}
        material={materials['Material.006']}
      />
      <mesh geometry={nodes.Cube017_2.geometry} material={materials.Material} />
    </group>
  );
}

useGLTF.preload('/models/mech-keyboard-transformed.glb');
