/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: { Cube010: THREE.Mesh; Cube010_1: THREE.Mesh; Cube010_2: THREE.Mesh };
  materials: {
    ['Mouse - Shiny Grey']: THREE.MeshStandardMaterial;
    ['Mouse - Mat Grey']: THREE.MeshStandardMaterial;
    ['Mouse - Wheel Grey']: THREE.MeshStandardMaterial;
  };
};

export function MouseModel(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/mouse.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials['Mouse - Shiny Grey']}
      />
      <mesh
        geometry={nodes.Cube010_1.geometry}
        material={materials['Mouse - Mat Grey']}
      />
      <mesh
        geometry={nodes.Cube010_2.geometry}
        material={materials['Mouse - Wheel Grey']}
      />
    </group>
  );
}

useGLTF.preload('/models/mouse.glb');
