/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Sphere007001: THREE.Mesh;
    Sphere007001_1: THREE.Mesh;
    Sphere007001_2: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    ['3']: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshPhysicalMaterial;
  };
};

export function OfficeChair(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/office_chair-transformed.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere007001.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Sphere007001_1.geometry}
        material={materials['3']}
      />
      <mesh
        geometry={nodes.Sphere007001_2.geometry}
        material={materials.PaletteMaterial002}
      />
    </group>
  );
}

useGLTF.preload('/models/office_chair-transformed.glb');
