/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { ThreeElements } from '@react-three/fiber';
import type { GLTF } from 'three-stdlib';
import { useMemo } from 'react';

type GLTFResult = GLTF & {
  nodes: {
    Sphere007001: THREE.Mesh;
    Sphere007001_1: THREE.Mesh;
    Sphere007001_2: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    ['3']: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshPhysicalMaterial;
  };
};

export function OfficeChairModel(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/office-chair-transformed.glb',
  ) as unknown as GLTFResult;

  const armrestMaterial = useMemo(() => {
    const src = materials.PaletteMaterial002;
    const mat = new THREE.MeshStandardMaterial({
      color: src.color,
      roughness: src.roughness,
      metalness: src.metalness,
      map: src.map,
      normalMap: src.normalMap,
      aoMap: src.aoMap,
      transparent: false,
      depthWrite: true,
    });
    return mat;
  }, [materials.PaletteMaterial002]);

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.031]}>
        <mesh
          geometry={nodes.Sphere007001.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Sphere007001_1.geometry}
          material={materials['3']}
        />
        <mesh
          geometry={nodes.Sphere007001_2.geometry}
          material={armrestMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/office-chair-transformed.glb');
